import esbuild from "esbuild";

const banner = `#!/usr/bin/env node
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Obsidian LLM Bridges MCP Server
*/
`;

await esbuild.build({
  banner: {
    js: banner,
  },
  entryPoints: ["src/mcp-server.ts"],
  bundle: true,
  platform: "node",
  target: "node18",
  format: "esm",
  outfile: "dist/mcp-server.js",
  external: [],
  minify: false,
  sourcemap: false,
});

console.log("MCP server built successfully");
